# Generated by Django 4.1.4 on 2022-12-26 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_entr'),
    ]

    operations = [
        migrations.AddField(
            model_name='entr',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
