# Generated by Django 4.1.4 on 2022-12-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_entr_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='entr',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to='user'),
        ),
        migrations.AddField(
            model_name='user',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to='user'),
        ),
    ]
