# Generated by Django 4.1.4 on 2022-12-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='realisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=None)),
                ('thumb', models.ImageField(blank=True, null=True, upload_to='realisation')),
            ],
        ),
    ]
