# Generated by Django 4.1.4 on 2022-12-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realisation',
            name='entr',
            field=models.CharField(default=None, max_length=150, null=None),
        ),
    ]
