# Generated by Django 4.1.4 on 2022-12-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Give',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('numberItems', models.IntegerField(default=0)),
                ('giver', models.CharField(max_length=120)),
                ('inStock', models.BooleanField(default=True)),
            ],
        ),
    ]
