# Generated by Django 4.1.4 on 2022-12-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='give',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to='dons'),
        ),
    ]
